package we.josemipepeedu.casisi.Screen.Ruleta.Objetos;

public enum Apuestas {
	NUMEROSCUBIERTOS18,
	NUMEROSCUBIERTOS12,
	NUMEROSCUBIERTOS6,
	NUMEROSCUBIERTOS4,
	NUMEROSCUBIERTOS3,
	NUMEROSCUBIERTOS2,
	NUMEROSCUBIERTOS1
}
